### ISSUE TITLE
GenericPretty-1.2.1 does not compile with GHC 8.4.1

### ISSUE THREAD

**Issue by peti** [RazvanRanca/GenericPretty#2]
The errors are:

~~~
Text/PrettyPrint/GenericPretty.hs:127:33: error:
    Ambiguous occurrence ‘<>’
    It could refer to either ‘Prelude.<>’,
                             imported from ‘Prelude’ at Text/PrettyPrint/GenericPretty.hs:18:8-37
                             (and originally defined in ‘GHC.Base’)
                          or ‘Text.PrettyPrint.<>’,
                             imported from ‘Text.PrettyPrint’ at Text/PrettyPrint/GenericPretty.hs:29:1-23
                             (and originally defined in ‘Text.PrettyPrint.HughesPJ’)
    |
127 |       | length s == 1 = [lparen <> head s <> rparen]
    |                                 ^^

Text/PrettyPrint/GenericPretty.hs:127:43: error:
    Ambiguous occurrence ‘<>’
    It could refer to either ‘Prelude.<>’,
                             imported from ‘Prelude’ at Text/PrettyPrint/GenericPretty.hs:18:8-37
                             (and originally defined in ‘GHC.Base’)
                          or ‘Text.PrettyPrint.<>’,
                             imported from ‘Text.PrettyPrint’ at Text/PrettyPrint/GenericPretty.hs:29:1-23
                             (and originally defined in ‘Text.PrettyPrint.HughesPJ’)
    |
127 |       | length s == 1 = [lparen <> head s <> rparen]
    |                                           ^^
~~~

This seems to be caused by `base-4.11` exporting `<>` from `Prelude` now.

**Comment by RazvanRanca** [comment]
Pushed to hackage. Thanks for the help.
